const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('node:fs');const path=require('node:path');
(async()=>{
  const root=path.resolve('.');const out=path.join(root,'docs/evidencias');fs.mkdirSync(out,{recursive:true});
  process.env.TEMP=path.join(root,'.qa');process.env.TMP=process.env.TEMP;fs.mkdirSync(process.env.TEMP,{recursive:true});
  const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--disable-gpu','--no-first-run']});
  const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:3001');await page.locator('#detail h2').waitFor();
  await page.screenshot({path:path.join(out,'01-visor.png'),fullPage:true});
  await page.getByLabel('Buscar un punto',{exact:true}).fill('Biblioteca');
  if(await page.locator('.point-card').count()!==1)throw Error('Filtro inconsistente');
  await page.getByLabel('Buscar un punto',{exact:true}).fill('');
  const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Descargar informe PDF'}).click();
  await (await downloadPromise).saveAs(path.join(out,'informe-ejemplo.pdf'));
  await page.getByRole('button',{name:'Acceso al equipo'}).click();
  await page.getByLabel('Usuario',{exact:true}).fill('admin.demo');
  await page.getByLabel('Contraseña',{exact:true}).fill('Demostracion-Local-2026!');
  await page.getByRole('button',{name:'Crear cuenta administradora'}).click();
  await page.getByRole('button',{name:'Nuevo punto'}).waitFor();
  await page.getByRole('button',{name:'Nuevo punto'}).click();
  await page.getByLabel('Nombre del punto',{exact:true}).fill('Centro de prueba accesible');
  await page.getByLabel('Descripción',{exact:true}).fill('Punto ficticio para comprobar el formulario de administración.');
  await page.getByLabel('Nombre del contacto',{exact:true}).fill('Contacto Demostrativo');
  await page.getByLabel('Correo',{exact:true}).fill('contacto@example.invalid');
  await page.getByLabel('Teléfono',{exact:true}).fill('+56900000000');
  if(await page.locator('#contactEmail').getAttribute('type')!=='password')throw Error('Campo sin máscara');
  await page.getByRole('button',{name:'Mostrar correo',exact:true}).click();
  if(await page.locator('#contactEmail').getAttribute('type')!=='text')throw Error('Ojito no revela');
  await page.getByRole('button',{name:'Mostrar correo',exact:true}).click();
  await page.locator('#pointDialog').screenshot({path:path.join(out,'02-formulario-protegido.png')});
  await page.getByRole('button',{name:'Guardar punto',exact:true}).click();
  await page.getByRole('heading',{name:'Centro de prueba accesible',exact:true}).waitFor();
  if((await page.locator('#detail').textContent()).includes('contacto@example.invalid'))throw Error('Contacto revelado automáticamente');
  await page.getByRole('button',{name:'Mostrar Correo',exact:true}).click();
  await page.getByText('contacto@example.invalid',{exact:true}).waitFor();
  await page.screenshot({path:path.join(out,'03-revelado-autorizado.png'),fullPage:true});
  await page.waitForTimeout(15500);
  if((await page.locator('#detail').textContent()).includes('contacto@example.invalid'))throw Error('Contacto sigue visible');
  await page.getByRole('button',{name:'Administración',exact:false}).click();
  await page.getByRole('heading',{name:'Actividad reciente'}).waitFor();
  await page.screenshot({path:path.join(out,'04-administracion.png'),fullPage:true});
  await page.getByRole('button',{name:'Directorio de puntos'}).click();
  await page.getByRole('heading',{name:'Directorio territorial'}).waitFor();
  await page.getByRole('button',{name:'Informes',exact:false}).first().click();
  await page.getByRole('heading',{name:'Informes generados'}).waitFor();
  await page.getByRole('button',{name:'Visor territorial',exact:false}).click();
  await page.setViewportSize({width:360,height:800});
  await page.screenshot({path:path.join(out,'05-movil.png'),fullPage:true});
  const dimensions=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));
  if(dimensions.scroll>dimensions.width)throw Error('Desbordamiento móvil: '+JSON.stringify(dimensions));
  if(errors.length)throw Error('Errores JS: '+errors.join('; '));
  fs.writeFileSync(path.join(out,'navegacion.json'),JSON.stringify({date:new Date().toISOString(),result:'aprobado',viewportDesktop:'1440x1100',viewportMobile:'360x800',cases:['filtro','descarga PDF','configuración inicial','creación de punto','máscara al escribir','ojito de entrada','revelado autorizado','ocultación a los 15 s','administración','directorio','informes','sin desbordamiento móvil','sin errores JavaScript'],errors},null,2));
  console.log('NAVEGACION_APROBADA');await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
