!pragma layout smetana
skinparam backgroundColor white
skinparam shadowing false
skinparam defaultFontName Arial
skinparam defaultFontSize 18
skinparam ArrowColor #42594C
skinparam LineColor #42594C
skinparam dpi 150
skinparam roundcorner 8
skinparam classBackgroundColor #F2F5EF
skinparam classBorderColor #42594C
skinparam classFontColor #18392F
skinparam sequenceParticipantBackgroundColor #F2F5EF
skinparam sequenceParticipantBorderColor #42594C
skinparam sequenceLifeLineBorderColor #819381
skinparam activityBackgroundColor #F2F5EF
skinparam activityBorderColor #42594C
skinparam noteBackgroundColor #FAF9F2
skinparam noteBorderColor #B7BCA8
